version: 2.1
jobs:
  build:
    executor: 
      name: python/default
      tag: "3.9"
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - python/install-packages:
          args: pytest
          pkg-manager: pip
          pypi-cache: false
      - run:
          command: |
            pytest
          name: Test
orbs:
  python: circleci/python@2.1.1
workflows:
  main:
    jobs:
      - build
